### ISSUE TITLE
Shuffling is broken on large datasets

### ISSUE THREAD

**Issue by dmadisetti** [NREL/Phase-space-sampling#3]
Hello,

The shuffling flag causes an int overflow for mpi communication on large datasets. Stack trace:

```
Traceback (most recent call last):
  File "main_iterative.py", line 75, in <module>
    data_to_downsample_, working_data, nFullData = prepareData(inpt)
  File "utils/dataUtils.py", line 109, in prepareData
    par.parallel_shuffle(data_to_downsample_)
  File "utils/parallel.py", line 341, in parallel_shuffle
    Ashuffled_ = odd_even_sort(Ashuffled_)
  File "utils/parallel.py", line 333, in odd_even_sort
    data = exchange(data, rank, rank + 1)
  File "utils/parallel.py", line 315, in exchange
    comm.send(localdata, dest=recvrank)
  File "mpi4py/MPI/Comm.pyx", line 1406, in mpi4py.MPI.Comm.send
  File "mpi4py/MPI/msgpickle.pxi", line 211, in mpi4py.MPI.PyMPI_send
  File "mpi4py/MPI/msgpickle.pxi", line 147, in mpi4py.MPI.pickle_dump
  File "mpi4py/MPI/msgbuffer.pxi", line 50, in mpi4py.MPI.downcast
OverflowError: integer 2335285847 does not fit in 'int'
Traceback (most recent call last):
  File "main_iterative.py", line 75, in <module>
    data_to_downsample_, working_data, nFullData = prepareData(inpt)
  File "utils/dataUtils.py", line 109, in prepareData
    par.parallel_shuffle(data_to_downsample_)
  File "utils/parallel.py", line 341, in parallel_shuffle
    Ashuffled_ = odd_even_sort(Ashuffled_)
  File "utils/parallel.py", line 333, in odd_even_sort
    data = exchange(data, rank, rank + 1)
  File "utils/parallel.py", line 315, in exchange
    comm.send(localdata, dest=recvrank)
  File "mpi4py/MPI/Comm.pyx", line 1406, in mpi4py.MPI.Comm.send
  File "mpi4py/MPI/msgpickle.pxi", line 211, in mpi4py.MPI.PyMPI_send
  File "mpi4py/MPI/msgpickle.pxi", line 147, in mpi4py.MPI.pickle_dump
  File "mpi4py/MPI/msgbuffer.pxi", line 50, in mpi4py.MPI.downcast
OverflowError: integer 2335285847 does not fit in 'int'
```

**Comment by malihass** [comment]
Thanks for reporting this, could you please share the input file you used so I can reproduce the error?

**Comment by dmadisetti** [comment]
Sure,

```yaml
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
! ~~~~ Density estimation
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
# Number of repetitions for the probability map estimation (keep at 2)
num_pdf_iter : 2
pdf_method : NormalizingFlow


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
! ~~~~ Normalizing flow training
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !

# Number of epochs for each normalizing flow training
nEpochs :			50 50
# Batch size for normalizing flow training
batch_size_train :		2048 2048
# Subset of data on which training is done
nWorkingData : 			2e5 
# Subset of data used to adjust the sampling probability to the desired number of samples
# If nWorkingDataAdjustment < 0, all data with the prescribed frequency is used
nWorkingDataAdjustment :        1e5
data_freq_adjustment :          10
# Learning rate during normalizing flow training
learning_rate : 		2e-4 2e-4
# Use GPU
use_gpu :                       True

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
! ~~~~ Normalizing flow architecture
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !

nCouplingLayer :		2  2  
num_bins : 			4  8
hidden_features :		12 12 
num_blocks :			3  3

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
! ~~~~ Density evaluation
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !

# Batch size for evaluation of density
batch_size_eval :		2.5e4

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
! ~~~~ Reproducibility
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !

seed :				42

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
! ~~~~ Timer
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !

printTiming :			False

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
! ~~~~ Data
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !

dataFile :			data/unsampled_test.npz
nDimReduced : 			15
preShuffled :			False
scalerFile :			scale1.npz

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !
! ~~~~ Downsampling
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ !

# List of desired number of samples
nSamples : 5e3
# Compute criterion (expensive for large number of downsampled data)
computeDistanceCriterion : 	True
# Prefix of the NPZ file containing the downsampled data
prefixDownsampledData : 	example
```


and here's the diff from 2D input

```diff
14c14
< nEpochs :			50 50
---
> nEpochs :			30 30
18c18
< nWorkingData : 			2e5 
---
> nWorkingData : 			1e5 
21c21
< nWorkingDataAdjustment :        1e5
---
> nWorkingDataAdjustment :        1e6
60,63c60,62
< dataFile :			data/unsampled_test.npz
< nDimReduced : 			15
< preShuffled :			False
< scalerFile :			scale1.npz
---
> dataFile :			data/combustion2DToDownsampleSmall.npy
> preShuffled :			True
> scalerFile :			scaler.npz
70c69
< nSamples : 5e3
---
> nSamples : 			1e3 1e4 1e5
74c73,75
< prefixDownsampledData : 	example
---
> prefixDownsampledData : 	downSampledData 
> 
> 
```

My data input is $97288192 \times 15$

**Comment by malihass** [comment]
Thank, and how many cores did you use when you encountered the error?

**Comment by dmadisetti** [comment]
I used a single [Expanse](https://www.sdsc.edu/support/user_guides/expanse.html) gpu-shared node 
```
GPU Nodes
--
GPU Type | NVIDIA V100 SMX2
GPUs/node | 4
CPU Type | Xeon Gold 6248
Cores/socket | 20
Sockets | 2
Clock speed | 2.5 GHz
Flop speed | 34.4 TFlop/s
Memory capacity | *384 GB DDR4 DRAM
Local Storage | 1.6TB Samsung PM1745b NVMe PCIe SSD
```

Launched with: `mpiexec -np 4 python main_iterative.py config`

Here's the openmpi version and compile options:

```
openmpi/4.0.4       : Name : openmpi
openmpi/4.0.4       : Version : 4.0.4
openmpi/4.0.4       : Target : zen2
openmpi/4.0.4       : Short description : An open source Message Passing Interface implementation.
openmpi/4.0.4       : Configure options : --enable-shared --disable-silent-rules --disable-builtin-atomics --with-pmi=/cm/shared/apps/slurm/20.02.3 --enable-static --with-zlib=/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen2/gcc-10.2.0/zlib-1.2.11-rchx6la4w4coybgwftagexqeqwmsqlgo --enable-mpi1-compatibility --without-fca --without-ofi --without-verbs --with-ucx=/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen2/gcc-10.2.0/ucx-1.8.1-ryimmraoirkfxy4n3hgsr3tv4iryly3q --without-mxm --without-psm --without-knem --without-hcoll --without-cma --without-xpmem --without-psm2 --without-loadleveler --without-lsf --without-alps --without-tm --without-sge --with-slurm --disable-memchecker --with-lustre=/usr --with-hwloc=/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen2/gcc-10.2.0/hwloc-1.11.11-kwmqdgzyk36skm33xwsxa43mikyfiomh --disable-java --disable-mpi-java --without-cuda --enable-wrapper-rpath --disable-wrapper-runpath --disable-mpi-cxx --disable-cxx-exceptions --with-wrapper-ldflags=-Wl,-rpath,/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/lib/gcc/x86_64-pc-linux-gnu/10.2.0 -Wl,-rpath,/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/lib64
```

---

Works fine without the shuffle! I just ended up preshuffling my data and had no issues. Pretty happy with the results, will cite when we publish

**Comment by dmadisetti** [comment]
So that was the test set, I was able to run it on 172982272 x 15
Do you have an email aside from your gmail? (you can message me at madisetti@jhu.edu if you don't want to put your email in a public forum) I'll send you my results, there were a few things I noticed that were interesting and would maybe like some insight on.
I'm happy enough with the output, and likely won't rerun it again, but will keep `computeDistanceCriterion` in mind for future datasets!

Back in the queue for running shuffling. Memory usage also spikes with shuffling and gave me an OOM, so I bumped up the allocation to 100GB.

**Comment by dmadisetti** [comment]
It does not crash with the shuffling branch.
Are the indices in the output based on the shuffle or the original data? Quickly looking at the code, it looks the index points to the shuffled array.
